SETTING:
  User: jhkim
  Node: all.q@ngsnode1

WORK_PARAMETERS:
  input_path: /storage/home/jhkim/Projects/cbNIPT/GCX-cbNIPT_QC_Setup-2025-10-23/Resources/Rawdata/[sample_id]_R[read_info].fastq.gz
  work_dir_path: /storage/home/jhkim/Projects/cbNIPT/GCX-cbNIPT_QC_Setup-2025-10-23/Results
  
TASK_LIST:
  Rawdata_FastQC:
    input: 'dd'
    output: 'dd'

  Trimming_FastP:
    input: df
    output: df