SETTING:
  User: jhkim
  Node: all.q@ngsnode1

WORK_PARAMETERS:
  input_path: /storage/home/jhkim/Projects/cbNIPT/GCX-cbNIPT_QC_Setup-2025-10-23/Resources/Rawdata/WGS/{sample_id}_R{read}.fastq.gz
  work_dir_path: /storage/home/jhkim/Projects/cbNIPT/GCX-cbNIPT_QC_Setup-2025-10-23/Results
  
TASK_LIST:
  - Rawdata_FastQC:
      tool: fastqc
      INPUT:
        read1: "{sample_id}_R1.fastq.gz"
        read2: "{sample_id}_R2.fastq.gz"
      OUTPUT:
        dirname: 00_Rawdata_FastQC
      params:
        threads: 2 
        extract: True

  # - name: Trimdata_FastP
  #   type: fastp
  #   version: v0.0.1
  #   params:
  #     input: ["{sample_id}_R1.fastq.gz", "{sample_id}_R2.fastq.gz"]
  #     output: "{work_dir_path}/{sample_id}/01_Trim_Fastp"


